#name: Build & Test
#on: [push]
#
#jobs:
#    requestLicenseActivation:
#      name: Request manual activation file 🔑
#      runs-on: ubuntu-latest
#      steps:
#        - name: Request manual activation file
#          id: getManualLicenseFile
#          uses: webbertakken/unity-request-activation-file@v2.0-alpha-1
#          with:
#            unityVersion: 2019.4.8f1
#        - name: Expose as artifact
#          uses: actions/upload-artifact@v1
#          with:
#            name: ${{ steps.getManualLicenseFile.outputs.filePath }}
#            path: ${{ steps.getManualLicenseFile.outputs.filePath }}
name: Build Workflow


on: [push]

env:
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        #token: ${{ secrets.TOKEN }}
        lfs: true

    - name: Cache library
      uses: actions/cache@v2.1.1
      with:
        path: Library
        key: Library

    - name: Build for Android
      uses: webbertakken/unity-builder@v2.0-alpha-1
      with:
        customParameters: -batchmode
        unityVersion: 2019.4.8f1
        projectPath: UIWindows
        targetPlatform: Android
        #versioning: Semantic
        #androidVersionCode: 0
        androidKeystoreName: uiwindow.keystore
        androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
        androidKeyaliasName: uiwindows
        androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
        androidAppBundle: false
        buildsPath: Builds
        #buildMethod: BuildCommand.PerformBuild
        #customParameters: '-batchmode'

    - name: Store build artifact
      uses: actions/upload-artifact@v2.1.4
      with:
        name: Builds
        path: Builds
